//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DELETE_ERD
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER_PAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUSTOMER_PAR()
        {
            this.CUSTOMER_PAR1 = new HashSet<CUSTOMER_PAR>();
            this.CUSTOMER_PAR_LINES = new HashSet<CUSTOMER_PAR_LINES>();
        }
    
        public int CUSTOMER_PAR_ID { get; set; }
        public int CUSTOMER_ID { get; set; }
        public Nullable<int> CUSTOMER_SUITE_ID { get; set; }
        public Nullable<int> INHERITED_CUSTOMER_PAR_ID { get; set; }
        public System.DateTime EFFECTIVE_START_DATE { get; set; }
        public Nullable<System.DateTime> EFFECTIVE_END_DATE { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public int CREATED_BY { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public int LAST_UPDATED_BY { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMER_PAR> CUSTOMER_PAR1 { get; set; }
        public virtual CUSTOMER_PAR CUSTOMER_PAR2 { get; set; }
        public virtual CUSTOMER_SUITE CUSTOMER_SUITE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMER_PAR_LINES> CUSTOMER_PAR_LINES { get; set; }
    }
}
