//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DELETE_ERD
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER_ADDRESS
    {
        public int CUSTOMER_ADDRESS_ID { get; set; }
        public int CUSTOMER_ID { get; set; }
        public string CUSTOMER_MASTER_PRIMARY_SITE_USE_FLAG { get; set; }
        public Nullable<int> CUSTOMER_MASTER_ADDRESS_ORIG_SYSTEM_REF { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string ADDRESS3 { get; set; }
        public string ADDRESS4 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string COUNTY { get; set; }
        public string ZIP_CODE { get; set; }
        public string COUNTRY { get; set; }
        public System.DateTime EFFECTIVE_START_DATE { get; set; }
        public Nullable<System.DateTime> EFFECTIVE_END_DATE { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public int CREATED_BY { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public int LAST_UPDATED_BY { get; set; }
        public Nullable<int> CUSTOMER_ADDRESS_MASTER_ID { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
    }
}
