//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DELETE_ERD
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER_CREDIT_CARD_SUITE
    {
        public int CREDIT_CARD_SUITE_ID { get; set; }
        public int CREDIT_CARD_ID { get; set; }
        public int SUITE_ID { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public int CREATED_BY { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public int LAST_UPDATED_BY { get; set; }
    
        public virtual CUSTOMER_CREDIT_CARD CUSTOMER_CREDIT_CARD { get; set; }
        public virtual SUITE SUITE { get; set; }
    }
}
