//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DELETE_ERD
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER_CONTACT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUSTOMER_CONTACT()
        {
            this.CUSTOMER_CONTACT_PHONE = new HashSet<CUSTOMER_CONTACT_PHONE>();
            this.CUSTOMER_CONTACT_WEB_RESPONSIBILITY = new HashSet<CUSTOMER_CONTACT_WEB_RESPONSIBILITY>();
        }
    
        public int CONTACT_ID { get; set; }
        public int CUSTOMER_ID { get; set; }
        public int CUSTOMER_CONTACT_TYPE_ID { get; set; }
        public string TITLE { get; set; }
        public string NAME_FIRST { get; set; }
        public string NAME_LAST { get; set; }
        public string EMAIL_ADDRESS { get; set; }
        public string PHONE_PRIMARY { get; set; }
        public string PHONE_CELL { get; set; }
        public string PHONE_FAX { get; set; }
        public string PHONE_EMERGENCY { get; set; }
        public string SUITE_ADMIN { get; set; }
        public string WEB_LOGIN { get; set; }
        public string WEB_PASSWORD { get; set; }
        public string WEB_ACCESS { get; set; }
        public string WEB_STATUS { get; set; }
        public string WEB_CUSTOMER_HISTORY { get; set; }
        public string APPLY_SUITE_PREFERENCES { get; set; }
        public System.DateTime EFFECTIVE_START_DATE { get; set; }
        public Nullable<System.DateTime> EFFECTIVE_END_DATE { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public int CREATED_BY { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public int LAST_UPDATED_BY { get; set; }
        public Nullable<int> CONTACT_MASTER_ID { get; set; }
        public Nullable<int> CUSTOMER_MASTER_CONTACT_ORIG_SYSTEM_REF { get; set; }
        public Nullable<int> CUSTOMER_MASTER_CONTACT_PHONE_ORIG_SYSTEM_REF { get; set; }
        public Nullable<int> CONTACT_PHONE_MASTER_ID { get; set; }
    
        public virtual CUSTOMER_CONTACT_TYPE CUSTOMER_CONTACT_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMER_CONTACT_PHONE> CUSTOMER_CONTACT_PHONE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMER_CONTACT_WEB_RESPONSIBILITY> CUSTOMER_CONTACT_WEB_RESPONSIBILITY { get; set; }
    }
}
