//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DELETE_ERD
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER_CREDIT_CARD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUSTOMER_CREDIT_CARD()
        {
            this.CUSTOMER_CREDIT_CARD_SUITE = new HashSet<CUSTOMER_CREDIT_CARD_SUITE>();
        }
    
        public int CREDIT_CARD_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public int CUSTOMER_ID { get; set; }
        public string NAME { get; set; }
        public int CREDIT_CARD_TYPE_ID { get; set; }
        public string NUMBER { get; set; }
        public byte[] NUMBER_ENCRYPTED { get; set; }
        public string EXPIRATION { get; set; }
        public byte[] EXPIRATION_ENCRYPTED { get; set; }
        public string ZIP_CODE { get; set; }
        public string ON_FILE { get; set; }
        public string AUTHORIZED_SIGNERS { get; set; }
        public System.DateTime EFFECTIVE_START_DATE { get; set; }
        public Nullable<System.DateTime> EFFECTIVE_END_DATE { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public int CREATED_BY { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public int LAST_UPDATED_BY { get; set; }
        public Nullable<int> TOKEN_VAULT_ID { get; set; }
        public string ALL_SUITES { get; set; }
        public string ALL_MENUS { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMER_CREDIT_CARD_SUITE> CUSTOMER_CREDIT_CARD_SUITE { get; set; }
    }
}
