//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DELETE_ERD
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUSTOMER()
        {
            this.CUSTOMER_CONTACT_PHONE = new HashSet<CUSTOMER_CONTACT_PHONE>();
            this.CUSTOMER_PAR = new HashSet<CUSTOMER_PAR>();
            this.CUSTOMER_PREFERENCE = new HashSet<CUSTOMER_PREFERENCE>();
            this.CUSTOMER_SUITE_PREFERENCE = new HashSet<CUSTOMER_SUITE_PREFERENCE>();
            this.CUSTOMER_CREDIT_CARD = new HashSet<CUSTOMER_CREDIT_CARD>();
            this.CUSTOMER_ADDRESS = new HashSet<CUSTOMER_ADDRESS>();
            this.CUSTOMER_NOTE = new HashSet<CUSTOMER_NOTE>();
            this.CUSTOMER_SUITE = new HashSet<CUSTOMER_SUITE>();
        }
    
        public int CUSTOMER_ID { get; set; }
        public string CUSTOMER_MASTER_STATUS_FLAG { get; set; }
        public string CUSTOMER_MASTER_ORIG_SYSTEM_REF { get; set; }
        public int CUSTOMER_MASTER_NUMBER { get; set; }
        public string CUSTOMER_MASTER_PROFILE_CLASS { get; set; }
        public int CUSTOMER_MASTER_ID { get; set; }
        public string CREDIT_HOLD { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string PARENT_CUSTOMER_NAME { get; set; }
        public System.DateTime EFFECTIVE_START_DATE { get; set; }
        public Nullable<System.DateTime> EFFECTIVE_END_DATE { get; set; }
        public string CUSTOMER_TAX_REG_NBR { get; set; }
        public string CUSTOMER_TAX_ID { get; set; }
        public Nullable<int> CUSTOMER_CATEGORY_ID { get; set; }
        public Nullable<int> CUSTOMER_TYPE_ID { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public int CREATED_BY { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public int LAST_UPDATED_BY { get; set; }
        public string ATTRIBUTE1 { get; set; }
        public string ATTRIBUTE2 { get; set; }
        public string ATTRIBUTE3 { get; set; }
        public string ATTRIBUTE4 { get; set; }
        public string ATTRIBUTE5 { get; set; }
        public string ATTRIBUTE6 { get; set; }
        public string ATTRIBUTE7 { get; set; }
        public string ATTRIBUTE8 { get; set; }
        public string ATTRIBUTE9 { get; set; }
        public string ATTRIBUTE10 { get; set; }
        public string ATTRIBUTE11 { get; set; }
        public string ATTRIBUTE12 { get; set; }
        public string ATTRIBUTE13 { get; set; }
        public string ATTRIBUTE14 { get; set; }
        public string ATTRIBUTE15 { get; set; }
        public Nullable<System.DateTime> SAP_CUTOVER { get; set; }
        public Nullable<int> LOCATION_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMER_CONTACT_PHONE> CUSTOMER_CONTACT_PHONE { get; set; }
        public virtual CUSTOMER_CATEGORY CUSTOMER_CATEGORY { get; set; }
        public virtual CUSTOMER_TYPE CUSTOMER_TYPE { get; set; }
        public virtual CUSTOMER_GENERAL_PREFERENCES CUSTOMER_GENERAL_PREFERENCES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMER_PAR> CUSTOMER_PAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMER_PREFERENCE> CUSTOMER_PREFERENCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMER_SUITE_PREFERENCE> CUSTOMER_SUITE_PREFERENCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMER_CREDIT_CARD> CUSTOMER_CREDIT_CARD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMER_ADDRESS> CUSTOMER_ADDRESS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMER_NOTE> CUSTOMER_NOTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMER_SUITE> CUSTOMER_SUITE { get; set; }
    }
}
