//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DELETE_ERD
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER_SUITE_NOTE
    {
        public int CUSTOMER_ID { get; set; }
        public int SUITE_ID { get; set; }
        public System.DateTime EFFECTIVE_START_DATE { get; set; }
        public int NOTE_ID { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public int CREATED_BY { get; set; }
    }
}
