//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DELETE_ERD
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER_PREFERENCE_LIST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUSTOMER_PREFERENCE_LIST()
        {
            this.CUSTOMER_PREFERENCE = new HashSet<CUSTOMER_PREFERENCE>();
            this.CUSTOMER_PREFERENCE_LOCATION_DETAILS = new HashSet<CUSTOMER_PREFERENCE_LOCATION_DETAILS>();
        }
    
        public int CUSTOMER_PREFERENCE_LIST_ID { get; set; }
        public string SHORT_DESCRIPTION { get; set; }
        public string DESCRIPTION { get; set; }
        public System.DateTime EFFECTIVE_START_DATE { get; set; }
        public Nullable<System.DateTime> EFFECTIVE_END_DATE { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public int CREATED_BY { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public int LAST_UPDATED_BY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMER_PREFERENCE> CUSTOMER_PREFERENCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMER_PREFERENCE_LOCATION_DETAILS> CUSTOMER_PREFERENCE_LOCATION_DETAILS { get; set; }
    }
}
