//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DELETE_ERD
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER_CONTACT_PHONE
    {
        public int CONTACT_PHONE_ID { get; set; }
        public int CONTACT_ID { get; set; }
        public int CUSTOMER_ID { get; set; }
        public string PHONE_PRIMARY { get; set; }
        public string PHONE_CELL { get; set; }
        public string PHONE_FAX { get; set; }
        public string PHONE_EMERGENCY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public int CREATED_BY { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public int LAST_UPDATED_BY { get; set; }
        public Nullable<int> CONTACT_PHONE_MASTER_ID { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual CUSTOMER_CONTACT CUSTOMER_CONTACT { get; set; }
    }
}
