//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DELETE_ERD
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER_SUITE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUSTOMER_SUITE()
        {
            this.CUSTOMER_PAR = new HashSet<CUSTOMER_PAR>();
        }
    
        public int CUSTOMER_SUITE_ID { get; set; }
        public int CUSTOMER_ID { get; set; }
        public int SUITE_ID { get; set; }
        public int LOCATION_ID { get; set; }
        public System.DateTime EFFECTIVE_START_DATE { get; set; }
        public Nullable<System.DateTime> EFFECTIVE_END_DATE { get; set; }
        public string VIP { get; set; }
        public string LIQUOR_RESTOCK { get; set; }
        public string LOCK_LIQUOR_CABINET { get; set; }
        public string LOCK_REFRIGERATOR { get; set; }
        public string DESSERT_CART { get; set; }
        public string COLLECT_CREDIT_CARD { get; set; }
        public string SUITE_ATTENDANT { get; set; }
        public int DISCOUNT_TYPE_ID { get; set; }
        public decimal DISCOUNT_AMOUNT { get; set; }
        public decimal DISCOUNT_PERCENTAGE { get; set; }
        public string NOTE { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public int CREATED_BY { get; set; }
        public System.DateTime LAST_UPDATED_DATE { get; set; }
        public int LAST_UPDATED_BY { get; set; }
        public string ATTRIBUTE1 { get; set; }
        public string ATTRIBUTE2 { get; set; }
        public string ATTRIBUTE3 { get; set; }
        public string ATTRIBUTE4 { get; set; }
        public string ATTRIBUTE5 { get; set; }
        public string ATTRIBUTE6 { get; set; }
        public string ATTRIBUTE7 { get; set; }
        public string ATTRIBUTE8 { get; set; }
        public string ATTRIBUTE9 { get; set; }
        public string ATTRIBUTE10 { get; set; }
        public string ATTRIBUTE11 { get; set; }
        public string ATTRIBUTE12 { get; set; }
        public string ATTRIBUTE13 { get; set; }
        public string ATTRIBUTE14 { get; set; }
        public string ATTRIBUTE15 { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMER_PAR> CUSTOMER_PAR { get; set; }
        public virtual SUITE SUITE { get; set; }
    }
}
